### ISSUE TITLE
Add ability to define filesystem when launching UAE debugging

### ISSUE THREAD

**Issue by tehKaiN** [BartmanAbyss/vscode-amiga-debug#7] opened 2020-06-06 20:56 UTC
Now since my library and games are building correctly, I still need one thing to be completely happy - ability to load files. Right now I see that there is a dh0 directory in extension's directory, which I assume is used to run the executable.

Would it be possible for extension to dynamically bind executable's original directory as UAE's main DH, so that when launching executable via debug task it'd be able to find files via relative paths?

**Comment by tehKaiN** [comment] 2020-06-07 07:40
I did some quick research and it seems that it's quite possible to add harddrive config via commandline param:

http://eab.abime.net/showthread.php?t=63719

- dh0 could be used as is
- dh1 could be mounted to executable's directory
- dh0's startup-sequence could be regenerated to use true executable name instead of runme.exe
- after all those there's no need to copy exe to dh0:runme.exe

Pretty please? It's probably the last thing I'll need ;)

**Comment by BartmanAbyss** [comment] 2020-06-07 09:25
The problem is, that "runme.exe" is hard-coded into WinUAE to detect the launch of the program for the debugger. I'm not sure how to do this any other way.
Re. Mounting other harddrives: You are free to change the configuration in WinUAE, just make sure to save it as "default", and it will be used every time the debugger is started. Does this work for you?

**Comment by tehKaiN** [comment] 2020-06-07 10:39
Yeah, but I have like 3 games which I'm actively working on and having to rename executable / rebind folder each time in uae config is a bit tedious.

I'm not a node.js guy but I've managed to do a bit of changes in amigaDebug.js. I've added:

```js
            const objdumpPath = path.join(binPath, "opt/bin/m68k-amiga-elf-objdump.exe");
            const dh0Path = path.join(binPath, "dh0/s/startup-sequence"); // <-- this is new
						const ssPath = path.join(dh0Path, "")
```

```js
            const objdumpPath = path.join(binPath, "opt/bin/m68k-amiga-elf-objdump.exe");
            const dh0Path = path.join(binPath, "dh0/s/startup-sequence"); // <-- this is new
            const ssPath = path.join(dh0Path, "") //  <-- this is new
            const runmePath = path.join(dh0Path, "runme.exe");
```

Which appears to properly generate the startup-sequence. I've not tested it yet, still need to do a dh1 thingy via uae params.

> The problem is, that "runme.exe" is hard-coded into WinUAE to detect the launch of the program for the debugger. I'm not sure how to do this any other way.

Perhaps executable name could be passed as param to uae so that it won't look for `runme.exe` but for other name?

**Comment by tehKaiN** [comment] 2020-06-07 14:33
I've implemented basic `cd` functionality here: https://github.com/AmigaPorts/amiga-cd - it does the job for that startup sequence.

So the only piece of puzzle remaining is to pass executable name to winuae which triggers debugging. I'm not familiar with uae codebase. Do you have any idea on where to start digging to have it passed as param or via config option?

**Comment by BartmanAbyss** [comment] 2020-06-07 14:42
unfortunately the WinUAE param parsing code is very complex. It took me ages... I have only implemented a new option for `config['debugging_features'] = 'gdbserver';` Maybe search for these terms?

**Comment by BartmanAbyss** [comment] 2020-06-07 20:07
merged. at least doesn't seem to break anything. next time, please test beforehand.

**Comment by tehKaiN** [comment] 2020-06-08 16:22
I can confirm that this works like a charm. I'll clean up my local changes and start a pull request!

**Closed** 2020-06-09 17:22 UTC
